Lesson03
FreeCourseJava/vv pull request #1
Opened 2022-07-08 13:58 UTC by ivtcro

1. Реализовать сортировку массива интов алгоритмом Coctail Shaker Sort
2. Переписать поиск числа в отсортированном массиве интов алгоритмом binary search используя рекурсию и копирование массива.

2022-07-08 14:58 UTC, hyragano requested changes

2022-07-08 21:40 UTC, eebelyaev commented on src/main/java/CocktailShaker.java
> +                for (int i = first; i < last -1 ; i++) {
Вот тут сработает, но это некрасиво. Переменная last по смыслу должна хранить последний индекс.

2022-07-09 06:47 UTC, ivtcro commented on src/main/java/BinarySearch.java
> +                return isElement(newArray, element);
я над этим думал, пробовал вынести вызов метода isElement чтобы остался только один, но мне не понравилось )
так как сейчас мне показалось более читабельным - не нужно разносить обявление массива newArray и его иницилизацию по разным местам, и сразу видно что все эти действия выполняются последовательно, не нужно разбираться в ветвлениях условий

2022-07-09 06:58 UTC, ivtcro commented on src/main/java/CocktailShaker.java
> +                for (int i = first; i < last -1 ; i++) {
согласен, поправил чтобы было красивее 
спасибо )

2022-07-09 07:29 UTC, ivtcro commented on src/main/java/CocktailShaker.java
> +        while (last > first) {
я сначала реализовывал алгоритм по какой-то визуализации
посмотрел описание - на самом деле по класике он ещё и оптимальней 
поправил алгоритм

2022-08-20 14:57 UTC, merged