Access modifiers
FreeCourseJava/vv pull request #3
Opened 2022-08-02 19:09 UTC by ivtcro

2022-08-08 20:15 UTC, hyragano requested changes

2022-08-08 20:15 UTC, hyragano commented on src/main/java/DynamicArray.java
> +    private int size;
Есть ли смысл использовать отдельную переменную для размера?

2022-08-08 20:15 UTC, hyragano commented on src/main/java/DynamicArray.java
> +    private Object[] list;
Это конечно мощьно. Правда нужен будет кастинг. это просто как коментарий не для исправления ессессно. Дальше будем изучать generics для улучшения момента кастинга, но в общей сложности все верно

2022-08-09 08:52 UTC, ivtcro commented on src/main/java/DynamicArray.java
> +    private int size;
тут не нужна
поправлю

2022-08-09 08:53 UTC, ivtcro commented on src/main/java/DynamicArray.java
> +    private Object[] list;
когда методы дёргаются, то кастинг там есть, например так
((Park) this.parks.getItem(i)).calcArea()

2022-08-20 14:57 UTC, merged